Parameters:
  ServerName:
    Description: "Enter the Name of Service the EC2 will be used for"
    Type: String
  InstanceTypeParameter:
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  KeyPair:
    Description: Name of Ec2 login key pair
    Type: AWS::EC2::KeyPair::KeyName

Mappings:
  AMIRegionMap: 
      us-east-1:
        MyAMI: ami-0ae8f15ae66fe8cda
      us-west-1:
        MyAMI: ami-0fda60cefceeaa4d3
      us-east-2:
        MyAMI: ami-05c3dc660cb6907f0

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: !FindInMap
        - AMIRegionMap
        - !Ref AWS::Region
        - MyAMI
      Tags:
        - Key: "Name"
          Value: !Ref ServerName
      SecurityGroups:
        - !Ref TestCloudFormSG
      KeyName: !Ref KeyPair


  TestCloudFormSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH && http from MyIP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0