#AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  KeyPair:
    Description: cicd stack key
    Type: "AWS::EC2::KeyPair::KeyName"
  MyIP:
    Description: Assigning IP
    Type: String
    Default: 97.176.108.57/32
Resources:
  S3RoleForCICD:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/vprofile-coco-cicd/stack-template/cicds3role.yaml
  JenkinsInst:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3RoleForCICD
    Properties:
      TemplateURL: https://s3.amazonaws.com/vprofile-coco-cicd/stack-template/jenk.yaml
      Parameters:
        KeyName: !Ref KeyPair
        MyIP: !Ref MyIP
  App01qa:
    Type: AWS::CloudFormation::Stack
    DependsOn: JenkinsInst
    Properties:
      TemplateURL: https://s3.amazonaws.com/vprofile-coco-cicd/stack-template/app01qa.yaml
      Parameters:
        KeyName: !Ref KeyPair
        MyIP: !Ref MyIP
  NexusServer:
    Type: AWS::CloudFormation::Stack
    DependsOn: JenkinsInst
    Properties:
      TemplateURL: https://s3.amazonaws.com/vprofile-coco-cicd/stack-template/nexus.yaml
      Parameters:
        KeyName: !Ref KeyPair
        MyIP: !Ref MyIP
  SonarServer:
    Type: AWS::CloudFormation::Stack
    DependsOn: JenkinsInst
    Properties:
      TemplateURL: https://s3.amazonaws.com/vprofile-coco-cicd/stack-template/sonar.yaml
      Parameters:
        KeyName: !Ref KeyPair
        MyIP: !Ref MyIP
  db01qa:
    Type: AWS::CloudFormation::Stack
    DependsOn: App01qa
    Properties:
      TemplateURL: https://s3.amazonaws.com/vprofile-coco-cicd/stack-template/db01qa.yaml
      Parameters:
        KeyName: !Ref KeyPair
        MyIP: !Ref MyIP
  WinTestServer:
    Type: AWS::CloudFormation::Stack
    DependsOn: JenkinsInst
    Properties:
      TemplateURL: https://s3.amazonaws.com/vprofile-coco-cicd/stack-template/wintest.yaml
      Parameters:
        KeyName: !Ref KeyPair
        MyIP: !Ref MyIP